### ISSUE TITLE
Which version of ubuntu and gazebo should I use to compiler the code?

### ISSUE THREAD

**Issue by aogrcs** [WindhoverLabs/airliner#45]
Dear
I used ubuntu 18.04 and gazebo9, but I found it hard to build the gazebo9 version and I could not build the develop version! Could you tell me which version I should use? Thanks!
Sincerely

**Comment by mbenson1** [comment]
The Ubuntu 18.04 and Gazebo 9 upgrade us still in development.  The master and develop branches still officially support Ubuntu 16.04 and Gazebo 8.  

The upgrade to Ubuntu 18.04 and 20.04 is trivial.  But the Gazebo 9 upgrade requires a development cycle to both upgrade the sensor/effector plugins and replace the vehicle models that were removed.  The Parrot Bebop2 model was completely removed.  Parrot vehicles are a simple port because we can use the POSIX OSAL and a simple PSP.  

Airliner was designed to be completely runtime reconfigurable.  Meaning apps and configurations can be added or completely replaced at runtime.  It also follows safety critical standards.  Which also means heap is not used, i.e. no dynamic memory allocation.  This, combined with the additional framework features, makes the memory foot print much bigger than an MCU typically provides.  

PX4 and Ardupilot come from Arduino heritage.  Arduino platforms typically have no more than 350kB of RAM.  Our smallest Airliner deployment to date is 4MB, though it could go smaller.  

Parrot drones are the platform I know of that include computing platforms with a real CPU and plenty of RAM to fit Airliner, and *had* a model in the Gazebo SITL repository.  We need to either find a suitable platform with a model, or we need to add a new model.  

In the meantime, either switch to Ubuntu 16 (we have a preconfigured vagrant box in the Atlas cloud), or remove the Gazebo plugin build and use JMavSim instead.  Fidelity is not as good and feature list is definitely not as good as Gazebo, but it runs fast enough to fly stable in a virtual machine.

**Comment by aogrcs** [comment]
Thanks Mathew, I will switch to ubuntu 16.04 and gazebo8 and try it! Such nice work!
Sincerely

**Comment by aogrcs** [comment]
Dear Mathew,
Why this link is unavailable
https://hangar.windhoverlabs.com/wiki/display/USR/Development+Environment+Setup
I tried ubuntu 16.04 and gazebo8, but I could not enter the gui desktop, it only worked for command line mode. Maybe the gpu driver crash! Have you ever seen this? Thanks
Sincerely

**Comment by aogrcs** [comment]
@mbenson1, Dear
The vagrant box worked, I built it successfully, thanks
